### ISSUE TITLE
Support output of binary files and C arrays

### ISSUE THREAD

**Issue by yeastplume** [yeastplume/aloevera#1]
At the moment, Aloevera only outputs basic data statements or assembly .byte statements, both of which need to be included as source. Although CA65 will let structure your output files however you like to create binary files from Aloevera's existing output, a logical next steps would be to add support for binary output directly from Aloevera (which can then be loaded however desired). Outputting C header files for CC65 would also be a nice addition.

**Comment by mattuna15** [comment]
Bin files for cx16 should have 2 bytes at the start to specify load address or 0x00,0x00 for user specified load address.

see this example from Matt Heffernan: 

```
if (argc >= 4) {
      sscanf(argv[3],"%x",&address);
   } else {
      // set default load address to 0x0000
      address = 0x0000;
   }

   odata = (uint8_t) (address & 0x00FF);
   fwrite(&odata,1,1,ofp);
   odata = (uint8_t) ((address & 0xFF00) >> 8);
   fwrite(&odata,1,1,ofp);
```

[ASC2BIN example](https://github.com/SlithyMatt/x16-chasevault/blob/master/asc2bin.c
)


I normally add it on myself using this sort of code: 

`printf "\x00\x00" | cat - tiles.bin > tiles.bin.new`

**Comment by mattuna15** [comment]
Tilemap .bin files will need to be formatted according to the metadata before export as they are loaded directly into vram using `VLOAD`. Is this possible?

**Comment by yeastplume** [comment]
First issue should be easy enough. Obviously no problem to add two bytes to bin output, and add a flag if the user wants to specify a load address.



> Tilemap .bin files will need to be formatted according to the metadata before export as they are loaded directly into vram using `VLOAD`. Is this possible?

Yes, I'd had this in mind as a 'conflated' mode of Tilemap output anyhow. The write metadata is obviously all there, so we just need to pad it with zeroes in the appropriate places to ensure the output matches target VERA Tilemap dimensions.

**Comment by mattuna15** [comment]
Hi looks ok for cc65 output apart from the missing "," at the end of the array lines.
```
 */
#ifndef PYRAMID_TILEMAP_H
#define PYRAMID_TILEMAP_H
static const unsigned char PYRAMID_TILEMAP[] = {
    0x01,0x00,0x02,0x00,0x03,0x00,0x1a,0x00 <-- Needs a "," here.
    0x1a,0x00,0x1a,0x00,0x1a,0x00,0x1a,0x00
    0x1a,0x00,0x1a,0x00,0x00,0x00,0x00,0x00

};
#endif
```

**Comment by yeastplume** [comment]
Thanks for catching, should be good now.

**Comment by yeastplume** [comment]
Think we're all good here now!

**Comment by mattuna15** [comment]
> yes looks good to me! Thanks
