### ISSUE TITLE
Inconsistent sizing figures for tilemaps

### ISSUE THREAD

**Issue by mattuna15** [yeastplume/aloevera#11]
In asm out put sizes seem to be fixed at 2400:
```
20200229 11:19:27.123 INFO aloevera::cmd::asm::command - Resource pal96 has size 192
20200229 11:19:27.156 INFO aloevera::cmd::asm::command - Resource game_tiles has size 18176
20200229 11:19:27.191 INFO aloevera::cmd::asm::command - Resource ui_tiles has size 19488
20200229 11:19:27.197 INFO aloevera::cmd::asm::command - Resource map001 has size 2400
20200229 11:19:27.204 INFO aloevera::cmd::asm::command - Resource ui_map has size 2400
```

Actual sizes are:
```
-rw-r--r--  1 mpe18  BSKYB\Domain Users  16386 29 Feb 11:19 map001.bin
-rw-r--r--  1 mpe18  BSKYB\Domain Users     55 29 Feb 11:19 map001.bin.meta
-rw-r--r--  1 mpe18  BSKYB\Domain Users   4098 29 Feb 11:19 ui_map.bin
-rw-r--r--  1 mpe18  BSKYB\Domain Users     53 29 Feb 11:19 ui_map.bin.meta
-rw-r--r--  1 mpe18  BSKYB\Domain Users  13742 29 Feb 11:19 map001.cc65.h
-rw-r--r--  1 mpe18  BSKYB\Domain Users  13741 29 Feb 11:19 ui_map.cc65.h
```

Meta:
```
;ui_map - size is 4096
;64x32 2 byte Tilemap entries
```

**Comment by mattuna15** [comment]
Not sure if related but tilemap seems to be truncating half of the tile set and returning to tile 00. If this was a memory issue I would expect garbage. But seems to be returning to the first tile.

Actual:
<img width="617" alt="Screenshot 2020-02-29 at 11 55 44" src="https://user-images.githubusercontent.com/16086727/75606999-99f46800-5aea-11ea-853e-61c0b42d3fe5.png">

Layout:
<img width="642" alt="Screenshot 2020-02-29 at 11 55 19" src="https://user-images.githubusercontent.com/16086727/75607000-9a8cfe80-5aea-11ea-8ee6-27c949fdddfd.png">

[Bin files](https://github.com/yeastplume/aloevera/files/4270243/ui_tiles.zip)

pngs:
![UI Map](https://user-images.githubusercontent.com/16086727/75607024-cdcf8d80-5aea-11ea-8bb8-b50a39e1359b.png)
![UI8x8ImageSet](https://user-images.githubusercontent.com/16086727/75607029-dde76d00-5aea-11ea-9d4e-65800df0bac6.png)

Palette:
![Matching palette](https://user-images.githubusercontent.com/16086727/75607210-88ac5b00-5aec-11ea-8ac9-e93a0d3dc86b.png)

**Comment by yeastplume** [comment]
In the first output

```
20200229 11:19:27.123 INFO aloevera::cmd::asm::command - Resource pal96 has size 192
20200229 11:19:27.156 INFO aloevera::cmd::asm::command - Resource game_tiles has size 18176
20200229 11:19:27.191 INFO aloevera::cmd::asm::command - Resource ui_tiles has size 19488
20200229 11:19:27.197 INFO aloevera::cmd::asm::command - Resource map001 has size 2400
20200229 11:19:27.204 INFO aloevera::cmd::asm::command - Resource ui_map has size 2400
```
The size being output here is the onscreen, non-conflated map size (40 x 30 x 2 bytes).

```
;ui_map - size is 4096
;64x32 2 byte Tilemap entries
```

The meta here is also correct, since once the tilemap is conflated, it matches VERA's map size, 64 x 32 x 2, or 4096. 

So I think the only issue here is that the info output is a bit confusing. It should output the actual target map size if the tilemap is being output in conflated mode.

Still trying to determine if there's an issue, so would like to ensure I can load that tileset, palette and imagemap correctly. Can you give me the exact mode you're running in, including any changes to scaling, start/stop in the display composer registers?

**Comment by mattuna15** [comment]
No scaling at the moment, mode 3 - 4bpp, 8x8 tiles. See if you can load it, I'll try a separate basic program as well.

Thanks for the info about the sizing.

```
vpoke(0x61, 0x1F3000); //enable
VERA.data0 = 0b000001; // 8X8 TILES, 64 X 32 TILES
VERA.data0 = 0xC0; //map base low
VERA.data0 = 0x63; //map base high  0x18F00
VERA.data0 = 0x00; //tile base low.
VERA.data0 = 0x00; //tilebase high. 0x0000
```

```	
...
#define MAP_BASE_1  0x8F00 //location 0x8F00 bank 0
#define TILE_BASE_1  0x0000 // loc 0 bank 0
...

cbm_k_setnam("src/imgs/imagesets/text.bin");
    cbm_k_setlfs(3,8,0);
    cbm_k_load(2,TILE_BASE_1); //vera bank 0

	//clear & init. ui layer 1
   cbm_k_setnam("src/imgs/tilemaps/uimap.bin"); 
    cbm_k_setlfs(3,8,0);
    cbm_k_load(3,MAP_BASE_1);  //vera bank 1
```

**Comment by yeastplume** [comment]
You'll likely need to set the screen scaling as well, but this is what I get. Those incorrect tiles look like incorrect Aloevera output, so will need to investigate.


![image](https://user-images.githubusercontent.com/7074070/75611376-e43d0f80-5b11-11ea-90e6-bbc60dc388cc.png)

**Comment by mattuna15** [comment]
Ok thanks. At least I'm not going mad. Let me know if you need anything else. I'm just experimenting with different looks and layers at the moment.

**Comment by yeastplume** [comment]
Turns out the high bits of the tile map indices weren't being set correctly. Try from latest master:

![image](https://user-images.githubusercontent.com/7074070/75611953-0b4a1000-5b17-11ea-93e6-bc582b54832b.png)

Do you mind if I use that tileset/images as part of the test data? It's handy to have a large tileset now for the integrated tests.

**Comment by mattuna15** [comment]
Yes of course please do. Glad you found it so quickly!

**Comment by mattuna15** [comment]
That fix is working. This can be closed now 👍

**Comment by yeastplume** [comment]
Great! Just leave this open for a bit to remind me to fix the info output for conflated tilemaps.
