### ISSUE TITLE
Support importing palettes in .gpl form

### ISSUE THREAD

**Issue by CJLove** [yeastplume/aloevera#13]
I'm just starting to experiment with using aloevera along with Piskel for a new X16 project. Piskel deals with palettes as Gimp .gpl files.  It would be great if aloevera would be able to import a palette which had been saved from Piskel or Gimp as a .gpl file.

In the interim I'll explore how to create a png file from a gpl file.

**Comment by yeastplume** [comment]
First, thanks for giving the tool a try and for the feedback, it's great to see another person getting some use out of it.

There's tons of graphic formats out there, and I've just gone with PNG for now as it's easily understood and can be exported by all graphics editors. I don't have particular plans to add support for application-specific formats at the moment, but if anyone else wants to take them I'd be happy to merge them.

**Comment by CJLove** [comment]
Understood.  I don't know rust (yet), but may take a stab at this in the future as I come up to speed on it.  Feel free to close or label as an enhancement.

**Comment by yeastplume** [comment]
Addressed by #18
