### ISSUE TITLE
Validation of include files

### ISSUE THREAD

**Issue by mattuna15** [yeastplume/aloevera#6]
Just wondering if it is worth putting a warning or error if the include files for the imageset, bitmap or spritesheets are too large to be included in low ram - maybe direct people to vload or to load into high ram banks?

**Comment by yeastplume** [comment]
Sure, sounds like a good idea. I think a warning would suffice along with a warning in the output metadata. It's still possible to use large resources in asm format in ca65 for instance, as you can still assemble them into files separate from your main code and load them separately.

**Comment by yeastplume** [comment]
Done now, just an output warning if a particular non-.BIN resource or total size of non-bin resources approaches or exceeds low ram size.
